name: Azure ARM

on: [push]

env:
 AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
 AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
 AZURE_LOCATION: westeurope

jobs:
  arm-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@master

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - uses: azure/arm-deploy@v1
      id: deploy
      with:
        scope: subscription
        region: ${{ env.AZURE_LOCATION }}
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
        template: ./main.bicep
        parameters: ./main.parameters.json rgLocation=${{ env.AZURE_LOCATION }} githubSecretsPat=${{ secrets.PAT }}
        failOnStdErr: false

    # - run: |
    #     acsAdminKey=${{ env.ACS_ADMIN_KEY }}
    #     keyId=$(curl \
    #     -H "Accept: application/vnd.github+json" \
    #     -H "Authorization: Bearer ${{ secrets.PAT }}" \
    #     https://api.github.com/orgs/developerschallenges/actions/secrets/public-key | jq -r '.key_id')
    #     curl -X PUT \
    #     -H "Accept: application/vnd.github+json" \
    #     -H "Authorization: Bearer ${{ secrets.PAT }}" \
    #     https://api.github.com/orgs/developerschallenges/actions/secrets/ACS_ADMIN_KEY \
    #     -d '{"encrypted_value":"'$acsAdminKey'","key_id":"'$keyId'","visibility":"all"}'
    #   env:
    #     ACS_ADMIN_KEY: ${{ steps.deploy.outputs.acsAdminKey }}