name: Azure ARM

on: [push]

env:
 AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
 AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
 AZURE_LOCATION: westeurope

jobs:
  arm-deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@master

    - run: |
        curl -X PUT \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/orgs/developerschallenges/actions/secrets/SECRET_NAME \
        -d '{"encrypted_value":"c2VjcmV0","visibility":"all"}' 

      # Log into Azure
    # - uses: azure/login@v1
    #   with:
    #     creds: ${{ env.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    # - uses: azure/arm-deploy@v1
    #   with:
    #     scope: subscription
    #     region: ${{ env.AZURE_LOCATION }}
    #     subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
    #     template: ./main.bicep
    #     parameters: ./main.parameters.json rgLocation=${{ env.AZURE_LOCATION }}
    #     failOnStdErr: false